spring:
  datasource:
    name: h2
  jpa:
    show-sql: false
  h2:
    console:
      enabled: true
      path: /h2-console
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
actconawa:
  repo: <path-to-.git>
