spring:
  datasource:
    name: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
  jmx:
    enabled: false
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2-console
  main:
    lazy-initialization: true
  application:
    admin:
      enabled: true
  sql:
    init:
      mode: never
  servlet:
    multipart:
      enabled: false
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
actconawa:
  repo: <path-to-.git>
logging:
  level:
    at.ac.tuwien.inso.actconawa: DEBUG
